{% set name = "hurry.filesize" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hurry.filesize-{{ version }}.tar.gz
  sha256: f5368329adbef86accd3bc9490522340bb79260455ae89b1a42c10f63801b9a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools

test:
  imports:
    - hurry
    - hurry.filesize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hurry.filesize/
  license: ZPL-2.1
  license_file: LICENSE.txt
  license_family: OTHER
  summary: Python library for human readable file sizes (or anything sized in bytes)

extra:
  recipe-maintainers:
    - iamthebot
    - rxm7706
    - raivivek
